#!/bin/sh

if [ -z $1 ] || [ -z $2 ]; then
cat << EOF
 This script runs the "rename_agents_in_xml" script for all
 ".xml" files in the specified directory.

 Usage:
   $0 SOURCE_DIR DEST_DIR
EOF
fi

script=" ./rename_agents_in_xml";

# Jeff's table of agent names
#
# See the TIC CVS repository
table="$COUGAAR_INSTALL_PATH/csmart/config/org_agent_builder/org_data/org_hierarchy.csv";

# where to find the xml files
src=$1;

# where to put the modified files
dest=$2;

if [ -z $table ] || [ ! -f $table ]; then
  echo "Unable to find agent rename table: $table";
  exit -1;
fi

if [ -z $src ] || [ ! -d $src ]; then
  echo "Source directory doesn't exist: $src";
  exit -1;
fi

if [ -z $dest ] || [ ! -d $dest ]; then
  echo "Destination directory doesn't exist: $dest";
  exit -1;
fi

for f in $src/*.xml; do 
  fn=`echo $f | sed -e 's/^.*\/\([^\/]*\)$/\1/'`;
  echo $fn;
  $script $table $f > $dest/$fn;
done
