#!/bin/sh

# <copyright>
#  
#  Copyright 2004 BBNT Solutions, LLC
#  under sponsorship of the Defense Advanced Research Projects
#  Agency (DARPA).
# 
#  You can redistribute this software and/or modify it under the
#  terms of the Cougaar Open Source License as published on the
#  Cougaar Open Source Website (www.cougaar.org).
# 
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
#  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
#  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
#  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
#  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#  
# </copyright>


if [ -z $1 ] || [ -z $2 ]; then
cat << EOF
 This script runs the "rename_agents_in_csv" script for all
 ".csv" files in the specified directory.

 Usage:
   $0 SOURCE_DIR DEST_DIR
EOF
fi

script="./rename_agents_in_csv";

# Jeff's table of agent names
#
# See the TIC CVS repository
table="$COUGAAR_INSTALL_PATH/csmart/config/org_agent_builder/1ad.org_data/org_hierarchy.csv";

# where to find the csv files
src=$1;

# where to put the modified files
dest=$2;

if [ -z $table ] || [ ! -f $table ]; then
  echo "Unable to find agent rename table: $table";
  exit -1;
fi

if [ -z $src ] || [ ! -d $src ]; then
  echo "Source directory doesn't exist: $src";
  exit -1;
fi

if [ -z $dest ] || [ ! -d $dest ]; then
  echo "Destination directory doesn't exist: $dest";
  exit -1;
fi

for f in $src/*.csv; do 
  fn=`echo $f | sed -e 's/^.*\/\([^\/]*\)$/\1/'`;
  echo $fn;
  $script $table $f > $dest/$fn;
done
