/* 
 * <copyright>
 * This software is to be used only in accordance with the COUGAAR license
 * agreement. The license agreement and other information can be found at
 * http://www.cougaar.org
 * 
 *       © Copyright 2001 by BBNT Solutions LLC.
 * </copyright>
 */
package org.cougaar.tools.csmart.ui.component;

import java.io.File;
import java.io.FileFilter;
import java.net.URL;

import org.cougaar.tools.csmart.ui.viewer.Organizer;
import org.cougaar.tools.server.ConfigurationWriter;

/**
 * Interface marking all Metric components.<br>
 * These are configurable components that can be added to an experiment.
 *
 */
public interface MetricComponent extends ModifiableComponent, ComponentProperties {

  void setName(String newName);

  String getMetricName();

  /**
   * Get the agents, both assigned and unassigned.
   * Only return new agents.
   * @return array of agent components
   */
  AgentComponent[] getAgents();

  /**
   * Return a file filter which can be used to fetch
   * the metrics files for this experiment.
   * @return file filter to get metrics files for this experiment
   */
  public FileFilter getResultFileFilter();

  /**
   * Return a file filter which can be used to delete
   * the files generated by this experiment.
   * @return file filter for cleanup
   */
  public FileFilter getCleanupFileFilter();

  /**
   * Get a configuration writer for this metric.
   * @param nodes the <code>NodeComponent[]</code> of the full experiment
   * @param nodeFileAddition a <code>String</code> to add Services to every Node file
   * @return a <code>ConfigurationWriter</code> to write out all config data for this metric
   */
  public ConfigurationWriter getConfigurationWriter(NodeComponent[] nodes, String nodeFileAddition);
}






